# Generated by Django 6.0.4 on 2026-05-05 17:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilySubProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner_supabase_uid', models.UUIDField(db_index=True)),
                ('full_name', models.CharField(max_length=150)),
                ('relationship', models.CharField(max_length=60)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('insurance_type', models.CharField(choices=[('life', 'Life'), ('medical', 'Medical'), ('motor', 'Motor'), ('travel', 'Travel'), ('other', 'Other')], default='other', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('storage_url', models.URLField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_by_supabase_uid', models.UUIDField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sub_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='api.familysubprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_with_supabase_uid', models.UUIDField(db_index=True)),
                ('shared_by_supabase_uid', models.UUIDField(db_index=True)),
                ('permission', models.CharField(choices=[('view', 'View'), ('claim_support', 'Claim Support'), ('manage', 'Manage')], default='view', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.policydocument')),
            ],
            options={
                'unique_together': {('policy', 'shared_with_supabase_uid')},
            },
        ),
    ]
