# Generated by Django 6.0.6 on 2026-06-14 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilySubProfileManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manager_supabase_uid', models.UUIDField(db_index=True)),
                ('granted_by_supabase_uid', models.UUIDField(db_index=True)),
                ('permission', models.CharField(choices=[('view', 'View'), ('claim_support', 'Claim Support'), ('manage', 'Manage')], default='manage', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='api.familysubprofile')),
            ],
            options={
                'unique_together': {('sub_profile', 'manager_supabase_uid')},
            },
        ),
    ]
